[package]
name = "ldpc-toolbox"
version = "0.1.0"
edition = "2018"
authors = ["Daniel Estevez <daniel@destevez.net>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand_chacha = "0.3"
rand = "0.8"
rand_core = "0.6"
rayon = "1.5"
